const safeStore={get:(k)=>{try{return localStorage.getItem(k)}catch(e){return null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}}};
const D = window.LEX_DATA;
const $ = (s, r=document) => r.querySelector(s);
const esc = (s='') => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm = (s='') => s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const state = { view:'home', params:{}, query:'', branchFilter:'', favorites:JSON.parse(safeStore.get('lex_favs')||'[]'), notes:JSON.parse(safeStore.get('lex_notes')||'{}') };

const coreSources = [
  ['Diario Oficial El Peruano — Normas actualizadas','https://diariooficial.elperuano.pe/normas/normasactualizadas','Normativa consolidada y modificaciones publicadas'],
  ['Archivo Digital de Legislación del Congreso','https://leyes.congreso.gob.pe/','Normas con rango de ley y archivo legislativo'],
  ['Tribunal Constitucional','https://www.tc.gob.pe/','Jurisprudencia constitucional'],
  ['Poder Judicial','https://www.pj.gob.pe/','Jurisprudencia y servicios judiciales'],
  ['Ministerio Público','https://www.gob.pe/mpfn','Fiscalías y servicios del Ministerio Público'],
  ['Ministerio de Justicia y Derechos Humanos','https://www.gob.pe/minjus','Información jurídica y servicios'],
  ['Indecopi','https://www.gob.pe/indecopi','Consumidor, competencia, propiedad intelectual y concursal'],
  ['SUNARP','https://www.gob.pe/sunarp','Servicios registrales'],
  ['SUNAT','https://www.sunat.gob.pe/','Tributos y aduanas'],
  ['SUNAFIL','https://www.gob.pe/sunafil','Inspección laboral'],
  ['OEFA','https://www.gob.pe/oefa','Fiscalización ambiental'],
  ['JNE','https://www.jne.gob.pe/','Justicia electoral'],
  ['ONPE','https://www.onpe.gob.pe/','Procesos electorales'],
  ['SBS','https://www.sbs.gob.pe/','Sistema financiero, seguros y pensiones'],
  ['SMV','https://www.smv.gob.pe/','Mercado de valores'],
  ['Migraciones','https://www.gob.pe/migraciones','Procedimientos migratorios']
];

const routeRules = [
  {keys:['alimento','pension aliment','manutencion'],branch:'Derecho de familia',matter:'Alimentos',authority:'Órgano jurisdiccional de familia/paz letrado que resulte competente conforme a materia y territorio.',way:'Proceso judicial de alimentos.',doc:'Demanda de alimentos.',route:['Identificar obligado y alimentista','Determinar competencia','Preparar demanda y anexos','Presentación','Calificación','Traslado / audiencia','Sentencia','Ejecución'],note:'La competencia territorial y requisitos exactos deben verificarse con los datos del caso y la normativa vigente.'},
  {keys:['estafa','robo','hurto','delito','denuncia penal','agresion'],branch:'Derecho penal',matter:'Denuncia / investigación penal',authority:'Ministerio Público y/o Policía Nacional del Perú, según el canal habilitado y la competencia del caso.',way:'Investigación penal.',doc:'Denuncia penal o comunicación de noticia criminal.',route:['Noticia criminal','Diligencias preliminares','Decisión fiscal','Investigación preparatoria, si corresponde','Etapa intermedia','Juicio, si corresponde'],note:'La fiscalía específica depende del lugar, materia, turno y especialidad.'},
  {keys:['multa municipal','municipalidad','sancion administrativa','papeleta administrativa'],branch:'Derecho administrativo',matter:'Impugnación administrativa',authority:'La propia entidad administrativa que emitió o tramita el acto, conforme a su TUPA y reglas de competencia.',way:'Procedimiento administrativo y, agotada la vía cuando corresponda, proceso contencioso-administrativo.',doc:'Recurso administrativo que corresponda (debe verificarse según acto y etapa).',route:['Notificación del acto','Revisar plazo y recurso','Presentación ante entidad','Resolución administrativa','Agotamiento de vía, si aplica','Control judicial'],note:'No se presume el recurso ni plazo sin revisar la resolución, TUPA y norma especial.'},
  {keys:['registrar propiedad','inscribir inmueble','sunarp','registro predio','propiedad inmueble'],branch:'Derecho registral',matter:'Inscripción registral',authority:'SUNARP / Oficina Registral competente, normalmente mediante título inscribible presentado al Registro.',way:'Procedimiento registral.',doc:'Título inscribible y solicitud de inscripción según el acto.',route:['Definir acto','Obtener título idóneo','Liquidar derechos','Presentar título','Calificación registral','Subsanación/observación si existe','Inscripción o recurso'],note:'Los requisitos dependen del acto: compraventa, sucesión, independización, hipoteca, etc.'},
  {keys:['banco','tarjeta','credito','prestamo bancario','cobro banco'],branch:'Derecho financiero del consumidor',matter:'Reclamo financiero',authority:'Proveedor financiero; según materia, Indecopi y/o entidad supervisora competente.',way:'Reclamo ante proveedor y mecanismos administrativos/judiciales que correspondan.',doc:'Reclamo o denuncia según la pretensión.',route:['Reunir contrato/estado de cuenta','Reclamo al proveedor','Revisar respuesta','Elegir vía competente','Impugnar si corresponde'],note:'Debe diferenciarse reclamo contractual/consumo, supervisión prudencial y controversia judicial.'},
  {keys:['despido','laboral','sueldo','beneficios sociales','empleador'],branch:'Derecho laboral',matter:'Conflicto laboral',authority:'SUNAFIL para inspección cuando corresponda y/o órgano jurisdiccional laboral para pretensiones judiciales.',way:'Inspección administrativa o proceso laboral, según objetivo.',doc:'Denuncia inspectiva o demanda laboral, según corresponda.',route:['Identificar régimen laboral','Reunir contrato/boletas','Definir pretensión','Elegir vía','Presentar','Audiencia / actuación','Decisión','Ejecución'],note:'La vía correcta depende del régimen, pretensión y urgencia.'},
  {keys:['consumidor','producto defectuoso','publicidad engañosa','indecopi'],branch:'Derecho del consumidor',matter:'Protección al consumidor',authority:'Proveedor y, según el caso, Indecopi.',way:'Reclamo y procedimiento de protección al consumidor.',doc:'Reclamo o denuncia de consumidor.',route:['Guardar comprobantes','Reclamo al proveedor','Evaluar solución','Denuncia si corresponde','Resolución','Recurso'],note:'Competencia y procedimiento dependen del tipo de infracción y pretensión.'},
  {keys:['impuesto','sunat','tributo','fiscalizacion tributaria'],branch:'Derecho tributario',matter:'Controversia tributaria',authority:'SUNAT u otra administración tributaria competente; Tribunal Fiscal en los casos que corresponda.',way:'Procedimiento tributario y posterior control judicial cuando proceda.',doc:'Reclamación, apelación u otra actuación según el acto.',route:['Identificar acto tributario','Revisar notificación','Verificar plazo','Reclamación si procede','Apelación si procede','Control judicial'],note:'Los plazos tributarios son especialmente sensibles: deben verificarse en la norma y acto concreto.'}
];

const procedures = [
  ['Alimentos','Derecho de familia','Judicial','Demanda → calificación → audiencia/actuación → sentencia → ejecución'],
  ['Denuncia penal','Derecho penal','Fiscal/Policial','Noticia criminal → diligencias → decisión fiscal → etapas posteriores si corresponde'],
  ['Impugnación administrativa','Derecho administrativo','Administrativa','Acto → recurso → resolución → agotamiento cuando aplique → control judicial'],
  ['Inscripción registral','Derecho registral','Registral','Título → presentación → calificación → subsanación/recurso → inscripción'],
  ['Protección al consumidor','Derecho del consumidor','Administrativa','Reclamo → denuncia → decisión → recurso'],
  ['Proceso laboral','Derecho procesal laboral','Judicial','Demanda → audiencia(s) → sentencia → impugnación → ejecución'],
  ['Proceso contencioso-administrativo','Derecho procesal administrativo','Judicial','Demanda → admisión → contradicción → decisión → recursos → ejecución'],
  ['Arbitraje','Derecho arbitral','Arbitral','Convenio → tribunal → actuaciones → laudo → anulación/ejecución cuando corresponda']
];

function navItems(){return [
 ['home','Inicio'],['branches','Mapa del Derecho'],['search','Buscador universal'],['where','¿Dónde presento?'],['procedures','Procedimientos'],['deadlines','Plazos'],['jurisprudence','Jurisprudencia'],['sources','Fuentes oficiales'],['templates','Modelos y checklists'],['updates','Actualizaciones'],['favorites','Favoritos y notas']
]}
function shell(content){
 document.querySelector('#app').innerHTML=`<div class="app"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brandmark">L360</div><div><h1>LEX PERÚ 360</h1><p>Sistema integral del Derecho peruano</p></div></div><div class="nav"><div class="group">Navegación</div>${navItems().map(([id,l])=>`<button data-view="${id}" class="${state.view===id?'active':''}">${l}</button>`).join('')}<div class="group">Estado</div></div><div class="sidebar-foot"><strong>Base inicial</strong><br>138 materias • 9 bloques<br><br><span class="badge ok">Contenido fuente cargado</span><br><br>Los campos procesales no verificados se identifican expresamente.</div></aside><main class="main"><header class="topbar"><button class="btn ghost mobile-menu" id="mobileMenu">☰</button><div class="top-search"><input id="globalSearch" placeholder="Buscar rama, caso, concepto o fuente…" value="${esc(state.query)}"></div><span class="pill">Perú • edición base 03/09/2026</span></header><div class="content">${content}<div class="footer">LEX PERÚ 360 • Base de conocimiento jurídica. Verifique la norma y la decisión íntegra antes de citar o actuar.</div></div></main></div>`;
 bindCommon();
}
function bindCommon(){
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));
 $('#mobileMenu')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
 const gs=$('#globalSearch'); if(gs) gs.onkeydown=e=>{if(e.key==='Enter'){state.query=gs.value.trim();go('search',{q:state.query})}};
 document.querySelectorAll('[data-branch]').forEach(el=>el.onclick=()=>go('branch',{n:+el.dataset.branch}));
 document.querySelectorAll('[data-source]').forEach(el=>el.onclick=()=>window.open(el.dataset.source,'_blank','noopener'));
}
function go(view,params={}){state.view=view;state.params=params; if(view==='search'&&params.q!==undefined)state.query=params.q; render(); window.scrollTo({top:0}); history.replaceState(null,'',`#${view}${params.n?'/'+params.n:''}`)}

function render(){
 const map={home:viewHome,branches:viewBranches,branch:viewBranch,search:viewSearch,where:viewWhere,procedures:viewProcedures,deadlines:viewDeadlines,jurisprudence:viewJurisprudence,sources:viewSources,templates:viewTemplates,updates:viewUpdates,favorites:viewFavorites};
 (map[state.view]||viewHome)();
}
function viewHome(){
 const blocks=D.blocks.map(b=>`<div class="card clickable" onclick="state.branchFilter='${esc(b.title)}';go('branches')"><span class="badge gold">Bloque ${b.roman}</span><h4>${esc(b.title)}</h4><p>${esc(b.description)}</p><div style="margin-top:10px" class="muted">Entradas ${b.start}–${b.end}</div></div>`).join('');
 shell(`<section class="hero"><div class="hero-card"><div class="eyebrow">Centro jurídico operativo</div><h2>Del problema jurídico a la ruta de actuación.</h2><p>Explora las 138 ramas y especialidades de la guía, sus casos emblemáticos y fuentes institucionales. Usa los módulos operativos para ubicar materia, vía, autoridad, procedimiento y puntos que deben verificarse oficialmente antes de actuar.</p><div class="actions"><button class="btn primary" onclick="go('where')">¿Dónde presento?</button><button class="btn" onclick="go('branches')">Explorar 138 ramas</button><button class="btn ghost" onclick="go('sources')">Fuentes oficiales</button></div></div><div class="stats"><div class="stat"><strong>138</strong><span>Ramas y especialidades</span></div><div class="stat"><strong>9</strong><span>Bloques jurídicos</span></div><div class="stat"><strong>${new Set(D.branches.map(x=>x.source)).size}</strong><span>Fuentes institucionales en la guía</span></div><div class="stat"><strong>100%</strong><span>Fichas base importadas</span></div></div></section><div class="verified">La información de enfoque, caso, hechos y enseñanza de cada ficha proviene de la guía cargada. La plataforma distingue expresamente esa base de los datos procesales que todavía requieran verificación oficial.</div><div class="section-title"><div><h3>Mapa del Derecho</h3><p>Nueve bloques para navegar de forma ordenada.</p></div></div><div class="grid">${blocks}</div><div class="section-title"><div><h3>Accesos operativos</h3><p>Herramientas para pasar del estudio a la actuación jurídica.</p></div></div><div class="grid">${[['¿Dónde presento?','Describe el problema y obtén una ruta preliminar de materia, autoridad, vía y documento.','where'],['Buscador universal','Busca simultáneamente ramas, casos emblemáticos, hechos, enseñanzas y fuentes.','search'],['Centro de plazos','Calcula días calendario o hábiles básicos y registra la regla jurídica antes de usar el resultado.','deadlines'],['Jurisprudencia base','Explora los casos emblemáticos incorporados en las 138 fichas.','jurisprudence'],['Fuentes oficiales','Accesos rápidos a repositorios normativos, jurisdiccionales y administrativos.','sources'],['Favoritos y notas','Crea tu propia capa de estudio y seguimiento en este dispositivo.','favorites']].map(x=>`<div class="card clickable" onclick="go('${x[2]}')"><h4>${x[0]}</h4><p>${x[1]}</p></div>`).join('')}</div>`)
}
function viewBranches(){
 const groups=['',...D.blocks.map(x=>x.title)];
 let items=D.branches.filter(b=>!state.branchFilter||b.block===state.branchFilter);
 shell(`<div class="section-title"><div><h3>138 ramas y especialidades</h3><p>Taxonomía inicial de la guía jurídica cargada.</p></div><span class="badge ok">${items.length} visibles</span></div><div class="toolbar"><input class="input" id="branchSearch" placeholder="Filtrar por nombre, enfoque o caso"><select class="select" id="blockFilter">${groups.map(g=>`<option value="${esc(g)}" ${state.branchFilter===g?'selected':''}>${g||'Todos los bloques'}</option>`).join('')}</select></div><div id="branchGrid" class="grid">${branchCards(items)}</div>`);
 $('#blockFilter').onchange=e=>{state.branchFilter=e.target.value;viewBranches()};
 $('#branchSearch').oninput=e=>{let q=norm(e.target.value);let x=D.branches.filter(b=>(!state.branchFilter||b.block===state.branchFilter)&&norm([b.name,b.focus,b.case,b.source].join(' ')).includes(q));$('#branchGrid').innerHTML=branchCards(x);bindCommon()}
}
function branchCards(items){return items.map(b=>`<div class="card clickable" data-branch="${b.number}"><span class="badge">${b.number} • ${esc(b.block)}</span><h4>${esc(b.name)}</h4><p>${esc(b.focus||'')}</p><div style="margin-top:12px"><span class="badge gold">${esc(b.source||'Fuente no indicada')}</span></div></div>`).join('')||`<div class="empty">No se encontraron resultados.</div>`}
function viewBranch(){
 const b=D.branches.find(x=>x.number===+state.params.n); if(!b)return go('branches');
 const fav=state.favorites.includes(b.number); const note=state.notes[b.number]||'';
 shell(`<div class="detail-head"><div><span class="badge gold">${b.number} • Bloque ${b.blockRoman} • ${esc(b.block)}</span><h2>${esc(b.name)}</h2><p>${esc(b.focus||'')}</p></div><button class="favorite ${fav?'on':''}" id="favBtn" title="Favorito">★</button></div><div class="detail-grid"><div class="stack"><div class="info"><h3>Caso real emblemático</h3><p><strong>${esc(b.case||'No indicado')}</strong></p></div><div class="info"><h3>¿Qué ocurrió?</h3><p>${esc(b.whatHappened||'No indicado')}</p></div><div class="info"><h3>Enseñanza principal</h3><p>${esc(b.lesson||'No indicada')}</p></div>${b.scopeNote?`<div class="warning"><strong>Nota de alcance de la guía:</strong> ${esc(b.scopeNote)}</div>`:''}<div class="info"><h3>Arquitectura jurídica de esta ficha</h3><div class="chips"><span class="badge warn">Normativa: pendiente de verificación por materia</span><span class="badge warn">Competencia: depende del caso</span><span class="badge warn">Plazos: verificar norma y acto</span><span class="badge warn">Modelos: requieren datos del caso</span></div><p style="margin-top:12px">El sistema evita inventar artículos o plazos. Usa “¿Dónde presento?” para generar una ruta preliminar y después contrástala con las fuentes oficiales.</p></div></div><aside class="stack"><div class="info"><h3>Fuente institucional indicada en la guía</h3><p>${esc(b.source||'No indicada')}</p>${b.sourceUrl?`<div class="actions"><button class="btn" data-source="${esc(b.sourceUrl)}">Abrir portal institucional</button></div>`:''}</div><div class="info"><h3>Mis notas</h3><textarea class="note-area" id="branchNote" placeholder="Agrega notas personales…">${esc(note)}</textarea><div class="actions"><button class="btn" id="saveNote">Guardar nota</button></div></div><div class="info"><h3>Acciones rápidas</h3><div class="actions"><button class="btn" onclick="state.query='${esc(b.name)}';go('search',{q:state.query})">Buscar relacionados</button><button class="btn" onclick="go('jurisprudence')">Jurisprudencia</button><button class="btn" onclick="go('sources')">Fuentes</button></div></div></aside></div>`);
 $('#favBtn').onclick=()=>{state.favorites=state.favorites.includes(b.number)?state.favorites.filter(x=>x!==b.number):[...state.favorites,b.number];safeStore.set('lex_favs',JSON.stringify(state.favorites));viewBranch()};
 $('#saveNote').onclick=()=>{state.notes[b.number]=$('#branchNote').value;safeStore.set('lex_notes',JSON.stringify(state.notes));$('#saveNote').textContent='Guardado ✓'};
}
function viewSearch(){
 let q=state.query||''; let nq=norm(q); let results=q?D.branches.filter(b=>norm([b.name,b.focus,b.case,b.whatHappened,b.lesson,b.source,b.block].join(' ')).includes(nq)):D.branches.slice(0,15);
 shell(`<div class="section-title"><div><h3>Buscador universal</h3><p>Busca en las 138 fichas base: rama, enfoque, caso, hechos, enseñanza y fuente.</p></div></div><div class="toolbar"><input class="input" id="pageSearch" placeholder="Ej.: prisión, consumidor, ambiental, arbitraje…" value="${esc(q)}"><button class="btn primary" id="doSearch">Buscar</button></div><div class="search-results" id="results">${resultCards(results,q)}</div>`);
 const run=()=>{state.query=$('#pageSearch').value.trim();viewSearch()}; $('#doSearch').onclick=run; $('#pageSearch').onkeydown=e=>{if(e.key==='Enter')run()}
}
function resultCards(results,q){return `<div class="muted" style="margin-bottom:8px">${results.length} resultado(s)${q?` para “${esc(q)}”`:''}</div>`+results.map(b=>`<div class="result" data-branch="${b.number}"><span class="badge">${b.number} • ${esc(b.block)}</span><strong>${esc(b.name)}</strong><small>${esc(b.focus)}</small><div style="margin-top:8px" class="muted">Caso: ${esc(b.case||'—')}</div></div>`).join('')}
function matchRoute(text){const t=norm(text);let best=null,score=0;for(const r of routeRules){let s=r.keys.reduce((a,k)=>a+(t.includes(norm(k))?1:0),0);if(s>score){score=s;best=r}}return score?best:null}
function viewWhere(){
 shell(`<div class="section-title"><div><h3>¿Dónde presento?</h3><p>Describe tu situación. El sistema genera una ruta preliminar y separa lo orientativo de lo que exige verificación concreta.</p></div></div><div class="card form-card"><label class="label">Describe el problema jurídico</label><textarea id="problem" placeholder="Ej.: quiero demandar alimentos para mi menor hijo; el demandado vive en…"></textarea><div class="split"><div><label class="label">Departamento / provincia (opcional)</label><input class="input" id="place" placeholder="Ej.: Chachapoyas, Amazonas"></div><div><label class="label">Objetivo (opcional)</label><input class="input" id="goal" placeholder="Ej.: cobrar, denunciar, apelar, inscribir"></div></div><div class="actions"><button class="btn primary" id="analyzeRoute">Analizar ruta</button></div></div><div id="routeAnswer"></div>`);
 $('#analyzeRoute').onclick=()=>{const text=$('#problem').value+' '+$('#goal').value; const r=matchRoute(text); const place=$('#place').value.trim(); $('#routeAnswer').innerHTML=r?routeAnswer(r,place):`<div class="card answer-card"><h3>Necesito clasificar mejor el problema</h3><p class="muted">No encontré una coincidencia suficientemente clara con las rutas operativas precargadas. Usa el Buscador Universal para identificar la rama o describe con más precisión el acto, entidad, documento recibido y tu objetivo.</p><div class="warning" style="margin-top:12px">No se asigna una autoridad ni un plazo por conjetura.</div></div>`;}
}
function routeAnswer(r,place){return `<div class="card answer-card"><div class="source-box"><div><span class="badge warn">Ruta preliminar • requiere verificación</span><h3>${esc(r.matter)}</h3></div><button class="btn" onclick="state.query='${esc(r.branch)}';go('search',{q:state.query})">Abrir materia</button></div><div class="kv"><div>Rama</div><div>${esc(r.branch)}</div><div>Autoridad</div><div>${esc(r.authority)}</div><div>Vía</div><div>${esc(r.way)}</div><div>Documento</div><div>${esc(r.doc)}</div><div>Ubicación informada</div><div>${esc(place||'No indicada')}</div></div><div class="route-flow">${r.route.map((x,i)=>`${i?'<span class="arrow">→</span>':''}<span class="step">${esc(x)}</span>`).join('')}</div><div class="warning" style="margin-top:16px"><strong>Control de seguridad jurídica:</strong> ${esc(r.note)} Antes de presentar, verificar norma vigente, competencia territorial, plazo, TUPA/aranceles y canal oficial.</div><div class="actions"><button class="btn" onclick="go('sources')">Ver fuentes oficiales</button><button class="btn" onclick="go('deadlines')">Centro de plazos</button></div></div>`}
function viewProcedures(){shell(`<div class="section-title"><div><h3>Procedimientos</h3><p>Rutas operativas iniciales. La plataforma no atribuye requisitos o plazos específicos sin fuente concreta.</p></div></div><div class="warning">Estas rutas describen la secuencia funcional general; no sustituyen la revisión del código, ley especial, TUPA o resolución aplicable.</div><div class="grid" style="margin-top:14px">${procedures.map(p=>`<div class="card"><span class="badge">${p[2]}</span><h4>${p[0]}</h4><p><strong>${p[1]}</strong></p><p style="margin-top:8px">${p[3]}</p><div style="margin-top:12px"><span class="badge warn">Plazos: verificar</span></div></div>`).join('')}</div>`)}
function addBusinessDays(start,days){let d=new Date(start+'T12:00:00');let n=0;while(n<days){d.setDate(d.getDate()+1);let day=d.getDay();if(day!==0&&day!==6)n++}return d}
function viewDeadlines(){shell(`<div class="section-title"><div><h3>Centro de plazos</h3><p>Herramienta matemática auxiliar. No determina por sí sola qué plazo jurídico corresponde.</p></div></div><div class="split"><div class="card"><h4>Calculadora básica</h4><label class="label">Fecha inicial</label><input type="date" class="input" id="startDate"><label class="label">Cantidad de días</label><input type="number" class="input" id="days" min="0" value="5"><label class="label">Tipo de cómputo</label><select class="select" id="dayType"><option value="calendar">Calendario</option><option value="business">Hábiles básicos (excluye sábado y domingo)</option></select><div class="actions"><button class="btn primary" id="calc">Calcular</button></div><div id="calcOut"></div></div><div class="card"><h4>Regla de uso profesional</h4><div class="timeline">${['Identificar la actuación y la norma','Confirmar qué evento inicia el cómputo','Confirmar días hábiles o calendario','Revisar feriados, suspensión y reglas especiales','Calcular y dejar constancia de la fuente'].map((x,i)=>`<div class="timeline-item"><div class="dot">${i+1}</div><div><strong>${x}</strong></div></div>`).join('')}</div><div class="warning" style="margin-top:14px">El modo “hábiles básicos” solo excluye sábados y domingos. No incorpora automáticamente feriados nacionales, locales, días no laborables judiciales ni suspensiones especiales.</div></div></div>`);$('#calc').onclick=()=>{let s=$('#startDate').value,n=+$ ('#days').value;if(!s)return;let d=new Date(s+'T12:00:00');if($('#dayType').value==='business')d=addBusinessDays(s,n);else d.setDate(d.getDate()+n);$('#calcOut').innerHTML=`<div class="verified" style="margin-top:14px">Resultado matemático: <strong>${d.toLocaleDateString('es-PE',{dateStyle:'full'})}</strong>. Verifica antes la regla jurídica aplicable.</div>`}}
function viewJurisprudence(){let rows=D.branches.map(b=>`<tr data-row><td>${b.number}</td><td><a class="link" data-branch="${b.number}">${esc(b.name)}</a></td><td>${esc(b.case||'')}</td><td>${esc(b.source||'')}</td><td>${b.scopeNote?'<span class="badge warn">Alcance especial</span>':'<span class="badge">Base guía</span>'}</td></tr>`).join('');shell(`<div class="section-title"><div><h3>Jurisprudencia y casos emblemáticos</h3><p>Índice de los casos incorporados en las 138 fichas de la guía.</p></div></div><div class="toolbar"><input class="input" id="jurSearch" placeholder="Filtrar expediente, caso, órgano o materia"></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Materia</th><th>Caso / expediente</th><th>Fuente indicada</th><th>Estado</th></tr></thead><tbody id="jurBody">${rows}</tbody></table></div>`);$('#jurSearch').oninput=e=>{let q=norm(e.target.value);document.querySelectorAll('#jurBody tr').forEach(tr=>tr.style.display=norm(tr.innerText).includes(q)?'':'none')}}
function viewSources(){shell(`<div class="section-title"><div><h3>Fuentes oficiales y repositorios</h3><p>Accesos rápidos para verificar normativa, jurisprudencia y procedimientos.</p></div></div><div class="verified">Para citar o presentar un escrito, utiliza la fuente específica del documento —no solo la página institucional— y comprueba vigencia, texto íntegro, modificatorias y fecha de consulta.</div><div class="source-list" style="margin-top:14px">${coreSources.map(s=>`<div class="source-item"><strong>${esc(s[0])}</strong><p class="muted">${esc(s[2])}</p><a href="${esc(s[1])}" target="_blank" rel="noopener">Abrir fuente ↗</a></div>`).join('')}</div>`)}
function viewTemplates(){const checklist=['Competencia material y territorial verificada','Petitorio preciso','Legitimidad de las partes','Hechos cronológicos y acreditables','Fundamento normativo vigente','Vía procedimental correcta','Medios probatorios pertinentes','Anexos identificados','Plazo revisado','Firma, casilla y tasas cuando correspondan'];shell(`<div class="section-title"><div><h3>Modelos y checklists</h3><p>Estructuras reutilizables sin inventar datos personales ni procesales.</p></div></div><div class="split"><div class="card"><h4>Checklist general de escrito</h4>${checklist.map(x=>`<label style="display:block;padding:7px 0;font-size:12px"><input type="checkbox"> ${esc(x)}</label>`).join('')}</div><div class="card"><h4>Estructura segura para una demanda</h4><div class="timeline">${['SUMILLA','SEÑOR JUEZ [POR COMPLETAR]','Datos de las partes [POR COMPLETAR]','PETITORIO','FUNDAMENTOS DE HECHO','FUNDAMENTOS DE DERECHO','MEDIOS PROBATORIOS','ANEXOS','POR TANTO'].map((x,i)=>`<div class="timeline-item"><div class="dot">${i+1}</div><div>${x}</div></div>`).join('')}</div><div class="warning" style="margin-top:14px">El módulo no completa juzgado, expediente, DNI, domicilio, cuantía o artículos sin datos y verificación.</div></div></div>`)}
function viewUpdates(){shell(`<div class="section-title"><div><h3>Actualizaciones jurídicas</h3><p>Centro de verificación manual conectado a repositorios oficiales.</p></div></div><div class="grid"><div class="card"><span class="badge ok">Normas</span><h4>El Peruano — Normas Legales Actualizadas</h4><p>Consulta textos compilados y modificaciones publicadas.</p><div class="actions"><button class="btn" data-source="https://diariooficial.elperuano.pe/normas/normasactualizadas">Abrir</button></div></div><div class="card"><span class="badge ok">Legislación</span><h4>Archivo Digital del Congreso</h4><p>Busca leyes, decretos legislativos, decretos de urgencia y otras normas con rango de ley.</p><div class="actions"><button class="btn" data-source="https://leyes.congreso.gob.pe/">Abrir</button></div></div><div class="card"><span class="badge warn">Próxima integración</span><h4>Historial de cambios automático</h4><p>La arquitectura está preparada para almacenar versiones, fecha de verificación y alertas cuando se conecte una base persistente.</p></div></div>`)}
function viewFavorites(){let favs=D.branches.filter(b=>state.favorites.includes(b.number));let notes=Object.entries(state.notes).filter(([,v])=>v.trim()).map(([k,v])=>({b:D.branches.find(x=>x.number===+k),v})).filter(x=>x.b);shell(`<div class="section-title"><div><h3>Favoritos y notas</h3><p>Guardados localmente en este navegador.</p></div></div><div class="split"><div><h4>Favoritos</h4><div class="search-results">${favs.length?favs.map(b=>`<div class="result" data-branch="${b.number}"><strong>${esc(b.name)}</strong><small>${esc(b.block)}</small></div>`).join(''):'<div class="empty">Aún no tienes favoritos.</div>'}</div></div><div><h4>Notas</h4><div class="search-results">${notes.length?notes.map(x=>`<div class="result" data-branch="${x.b.number}"><strong>${esc(x.b.name)}</strong><small>${esc(x.v.slice(0,180))}</small></div>`).join(''):'<div class="empty">Aún no tienes notas.</div>'}</div></div></div>`)}

window.go=go;window.state=state;
if(location.hash){const p=location.hash.slice(1).split('/');if(navItems().some(x=>x[0]===p[0])||p[0]==='branch'){state.view=p[0];if(p[0]==='branch')state.params.n=+p[1]}}
render();

