const SUPABASE_URL='https://vazrxoetkxrmidpvbtcv.supabase.co';
const SUPABASE_KEY='sb_publishable_ccMDbIW-xHgxAIaI4By-mw_8ve67jxG';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={session:null,page:'dashboard',authMode:'login',calendarDate:new Date(),channels:[],rows:{}};
const icon=()=>{try{lucide.createIcons()}catch(e){}};
const fmtDate=v=>v?new Date(v).toLocaleDateString('es-PE'):'—';
const fmtDateTime=v=>v?new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date(v)):'—';
const fmtTime12=v=>{if(!v)return '—';const [hh,mm='00']=String(v).slice(0,5).split(':'),h=Number(hh);if(!Number.isFinite(h))return String(v);return `${String(h%12||12).padStart(2,'0')}:${mm} ${h>=12?'PM':'AM'}`};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg,type='ok'){const d=document.createElement('div');d.className='toast '+(type==='err'?'err':type==='ok'?'ok':'');d.textContent=msg;$('#toasts').appendChild(d);setTimeout(()=>d.remove(),4200)}
function humanError(e){return e?.message||'Ocurrió un error inesperado.'}
const config={
clients:{title:'Clientes',sing:'cliente',desc:'Registro central de clientes, contactos y seguimientos.',icon:'users',order:'full_name',fields:[['full_name','Nombre completo','text',1],['document_number','DNI / RUC'],['email','Correo','email'],['phone','Teléfono','tel'],['address','Dirección'],['status','Estado','select',0,['Activo','Prospecto','Inactivo']],['follow_up_at','Próximo seguimiento','datetime12'],['notes','Notas','textarea']],cols:[['full_name','Cliente'],['document_number','DNI/RUC'],['phone','Teléfono'],['status','Estado'],['follow_up_at','Seguimiento','datetime']]},
cases:{title:'Casos',sing:'caso',desc:'Expedientes, prioridades, estados y responsables.',icon:'briefcase-business',order:'updated_at',fields:[['title','Título / nombre del caso','text',1],['case_number','N.º de expediente / caso'],['client_name','Cliente'],['matter','Materia'],['court','Órgano / entidad'],['status','Estado','select',0,['Activo','En trámite','Suspendido','Cerrado']],['priority','Prioridad','select',0,['Baja','Media','Alta','Urgente']],['responsible','Responsable'],['next_action_at','Próxima actuación','datetime12'],['description','Descripción','textarea']],cols:[['title','Caso'],['case_number','Expediente'],['client_name','Cliente'],['priority','Prioridad'],['status','Estado']]},
hearings:{title:'Audiencias',sing:'audiencia',desc:'Agenda de audiencias con fecha, hora, sede y estado.',icon:'gavel',order:'hearing_date',fields:[['title','Audiencia','text',1],['case_title','Caso / expediente relacionado'],['hearing_date','Fecha','date'],['hearing_time','Hora','time12'],['location','Sede / enlace'],['judge_or_authority','Juez / autoridad'],['status','Estado','select',0,['Programada','Realizada','Reprogramada','Cancelada']],['notes','Descripción / notas','textarea']],cols:[['title','Audiencia'],['case_title','Caso'],['hearing_date','Fecha'],['hearing_time','Hora','time12'],['status','Estado']]},
tasks:{title:'Tareas',sing:'tarea',desc:'Control de pendientes, vencimientos y responsables.',icon:'square-check-big',order:'due_at',fields:[['title','Tarea','text',1],['case_title','Caso relacionado'],['due_at','Vencimiento','datetime12'],['priority','Prioridad','select',0,['Baja','Media','Alta','Urgente']],['status','Estado','select',0,['Pendiente','En curso','Completada']],['assigned_to','Responsable'],['notes','Notas','textarea']],cols:[['title','Tarea'],['case_title','Caso'],['due_at','Vence','datetime'],['priority','Prioridad'],['status','Estado']]},
projects:{title:'Proyectos',sing:'proyecto',desc:'Proyectos internos, consultorías y encargos especiales.',icon:'folder-kanban',order:'updated_at',fields:[['name','Proyecto','text',1],['client_name','Cliente'],['status','Estado','select',0,['Planificado','Activo','En espera','Finalizado']],['priority','Prioridad','select',0,['Baja','Media','Alta']],['start_date','Inicio','date'],['end_date','Fin','date'],['owner','Responsable'],['description','Descripción','textarea']],cols:[['name','Proyecto'],['client_name','Cliente'],['status','Estado'],['priority','Prioridad'],['end_date','Fin']]},
events:{title:'Calendario',sing:'evento',desc:'Eventos, vencimientos y agenda jurídica del estudio.',icon:'calendar-days',order:'event_date',fields:[['title','Título','text',1],['type','Tipo','select',0,['Audiencia','Vencimiento','Reunión','Diligencia','Tarea','Otro']],['event_date','Fecha','date'],['start_time','Hora de inicio','time12'],['end_time','Hora de finalización','time12'],['description','Descripción completa','textarea'],['client_name','Cliente'],['case_title','Caso relacionado'],['case_number','Expediente'],['court','Órgano jurisdiccional'],['responsible','Responsable'],['modality','Modalidad','select',0,['Presencial','Virtual','Híbrida']],['location','Dirección / enlace de videoconferencia'],['priority','Prioridad','select',0,['Baja','Media','Alta','Urgente']],['status','Estado','select',0,['Programado','En curso','Completado','Cancelado']],['observations','Observaciones','textarea']],cols:[['title','Evento'],['event_date','Fecha'],['start_time','Hora','time12'],['type','Tipo'],['status','Estado']]},
reports:{title:'Reportes',sing:'reporte',desc:'Reportes guardados y notas de gestión.',icon:'file-chart-column',order:'created_at',fields:[['name','Nombre del reporte','text',1],['report_type','Tipo','select',0,['Casos','Audiencias','Tareas','Clientes','Productividad','Otro']],['period_start','Desde','date'],['period_end','Hasta','date'],['notes','Notas','textarea']],cols:[['name','Reporte'],['report_type','Tipo'],['period_start','Desde'],['period_end','Hasta']]},
documents:{title:'Documentos',sing:'documento',desc:'Archivo documental privado y relacionado con casos.',icon:'folder-open',order:'created_at',fields:[['name','Nombre del documento','text',1],['case_title','Caso relacionado'],['document_type','Tipo','select',0,['Escrito','Resolución','Contrato','Prueba','Informe','Otro']],['notes','Notas','textarea']],cols:[['name','Documento'],['document_type','Tipo'],['case_title','Caso'],['file_name','Archivo'],['created_at','Fecha','date']]}
}
function nowClock(){const n=new Date();$('#topDate').textContent=n.toLocaleDateString('es-PE',{timeZone:'America/Lima',weekday:'short',day:'2-digit',month:'short'});$('#topTime').textContent=n.toLocaleTimeString('es-PE',{timeZone:'America/Lima',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true});}setInterval(nowClock,1000);
async function init(){bindBase();try{const {data,error}=await sb.auth.getSession();if(error)console.warn(error);state.session=data?.session||null}catch(e){console.warn(e);state.session=null}if(state.session)showApp();else showAuth();sb.auth.onAuthStateChange((_e,s)=>{state.session=s;if(s)showApp();else showAuth()});}
function bindBase(){
$('#authForm').onsubmit=async e=>{e.preventDefault();const password=$('#authPassword').value;$('#authSubmit').disabled=true;$('#authSubmit').textContent='Ingresando…';try{const {error}=await sb.auth.signInWithPassword({email:'7366806822@untrm.edu.pe',password});if(error)throw error;toast('Acceso correcto.')}catch(err){toast('Contraseña incorrecta. Inténtalo nuevamente.','err')}finally{$('#authSubmit').disabled=false;$('#authSubmit').textContent='Ingresar'}};
$('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');
$('#userBtn').onclick=async()=>{await sb.auth.signOut();};
$('#notifBtn').onclick=()=>toggleNotifications();
$('#topAdd').onclick=()=>openModal(state.page==='dashboard'?'cases':state.page==='events'?'events':config[state.page]?state.page:'cases',null);
$('#quickCase').onclick=()=>openModal('cases',null);
$('#globalSearch').addEventListener('input',debounce(globalSearch,250));
$('#globalSearch').addEventListener('focus',()=>{if($('#globalResults').children.length)$('#globalResults').classList.remove('hidden')});
document.addEventListener('click',e=>{if(!e.target.closest('.searchbox'))$('#globalResults').classList.add('hidden');if(!e.target.closest('#notifBtn')&&!e.target.closest('#notifMenu'))$('#notifMenu').classList.add('hidden')});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(!b)return;navigate(b.dataset.page)});
}
function showAuth(){$('#app').classList.add('hidden');$('#auth').classList.remove('hidden');cleanupRealtime()}
function showApp(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');nowClock();navigate('dashboard');setupRealtime();loadNotifications();setupReminderEngine();icon()}
function navigate(p){state.page=p;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#sidebar').classList.remove('open');if(p==='dashboard')renderDashboard();else if(p==='events')renderCalendar();else renderCrud(p);icon()}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
async function getRows(table,order=config[table]?.order||'created_at',asc=false){let q=sb.from(table).select('*');if(order)q=q.order(order,{ascending:asc});const {data,error}=await q;if(error)throw error;return data||[]}
async function createRow(table,payload){const {data:{user}}=await sb.auth.getUser();const {data,error}=await sb.from(table).insert({...payload,created_by:user?.id||null}).select().single();if(error)throw error;await notifyDb('Registro creado',`Se registró ${config[table]?.sing||'un elemento'}.`,table,data.id);return data}
async function updateRow(table,id,payload){const {data,error}=await sb.from(table).update(payload).eq('id',id).select().single();if(error)throw error;await notifyDb('Registro actualizado',`Se actualizó ${config[table]?.sing||'un elemento'}.`,table,id);return data}
async function deleteRow(table,row){if(table==='documents'&&row.file_path){const {error:se}=await sb.storage.from('legal-documents').remove([row.file_path]);if(se)throw se}const {error}=await sb.from(table).delete().eq('id',row.id);if(error)throw error;toast('Registro eliminado.');await refreshCurrent()}
async function notifyDb(title,body,entity_type,entity_id){try{const {data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from('notifications').insert({title,body,entity_type,entity_id,created_by:user.id})}catch(e){console.warn(e)}}
function cleanupRealtime(){state.channels.forEach(c=>sb.removeChannel(c));state.channels=[]}
function setupRealtime(){cleanupRealtime();const tables=['clients','cases','hearings','tasks','documents','projects','events','reports','notifications'];tables.forEach(t=>{const ch=sb.channel('ea:'+t+':'+crypto.randomUUID()).on('postgres_changes',{event:'*',schema:'public',table:t},()=>{if(t==='notifications')loadNotifications();refreshCurrent();}).subscribe();state.channels.push(ch)})}